name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: 22

    - name: Set up JUnit 5
      run: |
        curl -L -o junit-platform-console-standalone.jar \
          https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.0/junit-platform-console-standalone-1.10.0.jar

    - name: Compile Java files
      run: |
        mkdir -p out
        find experiment -name "*.java" > sources.txt
        javac -d out @sources.txt

    - name: Run Tests
      run: |
        find experiment -name "*Test.java" > test_sources.txt || true
        if [ -s test_sources.txt ]; then
          javac -cp .:out:junit-platform-console-standalone.jar @test_sources.txt
          java -jar junit-platform-console-standalone.jar -cp out --scan-class-path
        else
          echo "No test files found."
        fi
